spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/websocketchat
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      hbm2ddl:
#        auto: update
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
